function Accurate_rate = Recognition_BoW_svm()
%     rootFolder = fullfile('Data\DataTrain');
%     imgSets = [ imageSet(fullfile(rootFolder, '0')), ...
%                 imageSet(fullfile(rootFolder, '1')), ...
%                 imageSet(fullfile(rootFolder, '2')), ...
%                 imageSet(fullfile(rootFolder, '3')), ...
%                 imageSet(fullfile(rootFolder, '4')), ...
%                 imageSet(fullfile(rootFolder, '5')), ...
%                 imageSet(fullfile(rootFolder, '6')), ...
%                 imageSet(fullfile(rootFolder, '7')), ...
%                 imageSet(fullfile(rootFolder, '8')), ...
%                 imageSet(fullfile(rootFolder, '9'))];
%     minSetCount = min([imgSets.Count]); 
%     imgSets = partition(imgSets, minSetCount, 'randomize');
%     bag = bagOfFeatures(imgSets);
%     save('MDL\bag_of_Features.mat','bag');
% %     load('MDL\bag_of_Features.mat');
%     categoryClassifier = trainImageCategoryClassifier(imgSets, bag);
%     save('MDL\categoryClassifier_BOW.mat','categoryClassifier');
% %     load('MDL\categoryClassifier_BOW.mat');
%     
%     rootFolder = fullfile('Data\DataTrain');
%     imgSets = [ imageSet(fullfile(rootFolder, '0')), ...
%                 imageSet(fullfile(rootFolder, '1')), ...
%                 imageSet(fullfile(rootFolder, '2')), ...
%                 imageSet(fullfile(rootFolder, '3')), ...
%                 imageSet(fullfile(rootFolder, '4')), ...
%                 imageSet(fullfile(rootFolder, '5')), ...
%                 imageSet(fullfile(rootFolder, '6')), ...
%                 imageSet(fullfile(rootFolder, '7')), ...
%                 imageSet(fullfile(rootFolder, '8')), ...
%                 imageSet(fullfile(rootFolder, '9'))];
%     confMatrix = evaluate(categoryClassifier, imgSets);
%     save('Results\confMatrix_BOW.mat','confMatrix');
    load('Results\confMatrix_BOW.mat');
    Accurate_rate=mean(diag(confMatrix))*100;
end